# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jeff B. Carter
email: jeff.b.carter@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Here you will find information about as well as thoughts and musings from
  Jeff B. Carter. Hope you enjoy!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jeffbcarter.com" # the base hostname & protocol for your site
twitter_username: snoski
github_username:  snoski

# Build settings
markdown: kramdown
